name: Publish package to PyPI

# Publishes to PyPI whenever a tag in the format "vX.X.X" is pushed.

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-test-and-publish:
    name: Build package and publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: ./scripts/build_test_container.sh

      - name: Run tests in Docker container
        run: ./scripts/test.sh

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install pypa/setuptools
        run: >-
          python -m
          pip install wheel

      # - name: Get version from tag name
      #   id: tag
      #   run: echo ::set-output name=TAG_NAME::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build a binary wheel
        run: >-
          python setup.py sdist bdist_wheel

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
