name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # # Set up Docker (this is usually done automatically on Ubuntu runners)
      # - name: Set up Docker
      #   uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: ./scripts/build_test_container.sh

      - name: Run tests in Docker container
        run: ./scripts/test.sh
